//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentID { get; set; }
        public int userID { get; set; }
        public System.DateTime com_datetime { get; set; }
        public string comment1 { get; set; }
        public int packageID { get; set; }
    
        public virtual package package { get; set; }
        public virtual user user { get; set; }
    }
}
