//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversationReply
    {
        public int crID { get; set; }
        public string reply { get; set; }
        public int userID { get; set; }
        public System.DateTime time { get; set; }
        public int cID { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual user user { get; set; }
    }
}
