//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GhoomoDbContext : DbContext
    {
        public GhoomoDbContext()
            : base("name=GhoomoDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<conversationReply> conversationReplies { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<scrabbook> scrabbooks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
