//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int imageID { get; set; }
        public string imagePath { get; set; }
        public int packageID { get; set; }
        public string Description { get; set; }
    
        public virtual package package { get; set; }
    }
}
