//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planmytrip
    {
        public int pmtID { get; set; }
        public string fullName { get; set; }
        public string Email { get; set; }
        public string contact { get; set; }
        public int persons { get; set; }
        public System.DateTime date { get; set; }
        public string depCity { get; set; }
        public Nullable<int> duration { get; set; }
        public string durFlex { get; set; }
        public string locations { get; set; }
        public string details { get; set; }
    }
}
